communication:
  proxyPort: '1234'
  serialport: COM4
  simulation: false
  simulationIP: 127.0.0.1
  simulationIPPort: '1234'
hubs:
  1818f42a:
  - 0
  - 1
  - 2
  - 3
  - 44
  - 45
  - 46
  - 47
  - 88
  - 89
  - 90
  - 91
  - 132
  - 133
  - 134
  - 135
  - 176
  - 177
  - 178
  - 179
  - 220
  - 221
  - 222
  - 223
